### PR TITLE
Changes done for Connectors

### PR DESCRIPTION
**Pull request by rahul-aggarwal-avalara**
Changes done specifically for the ease of use and compatibility with ERP
on Connector side

### CODE REVIEW

**Comment by jdmiller** [comment]
Please take a look @zfrolov

**Comment by zfrolov** [comment]
Built the nuget package, which only compiles for the dotnet 2.0 version of the project. The 4.5 and core 1.0 doesn't work, as the files added in this branch only apply to 2.0 for now.

**Comment by jdmiller** [comment]
@zfrolov Can we close this PR for now since we aren't looking to merge these into master in the near future?

**Comment by rahul-aggarwal-avalara** [comment]
Closing this as this is not required now. We are creating new pull request with the new changes we need to be merged.

**Pull request closed without merging**
